### ISSUE TITLE
Use of Hard-coded Password

### ISSUE THREAD

**Issue by selmankon** [ZekeriyaAY/dlk#1]
The software contains a hard-coded password, which it uses for its own inbound authentication or for outbound communication to external components.

https://github.com/ZekeriyaAY/dlk/blob/c60b0408329587d47898ad5eb3aba54a7a420954/Dockerfile#L21

References: https://cwe.mitre.org/data/definitions/259.html

**Comment by ZekeriyaAY** [comment]
This issue is not important. If you care enough re-open this issue and create proper pr for it.

> Gün gelir devran döner horoz do****r tavuk si**r.
> ~Cengiz Han
